parser: '@babel/eslint-parser'
extends:
  - airbnb
  - airbnb/hooks
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:jest-dom/recommended
  - plugin:prettier/recommended
env:
  browser: true
  node: true
  jest: true
plugins:
  - simple-import-sort
  - jss
rules:
  import/order: off
  import/prefer-default-export: off
  jest/no-mocks-import: off
  jss/sort-jss-keys: error
  jsx-a11y/label-has-associated-control:
    - error
    - assert: either
  react/jsx-props-no-spreading: off
  react/react-in-jsx-scope: off
  react/require-default-props:
    - error
    - ignoreFunctionalComponents: true
  simple-import-sort/exports: error
  simple-import-sort/imports: error
  sort-imports: off

overrides:
  - files:
      - config/**/*.js
      - src/utils/helpers/wdyr.js
      - src/utils/helpers/test-utils.jsx
    rules:
      import/no-extraneous-dependencies: off
      import/order:
        - error
        - newlines-between: always
      react/prop-types: off
      simple-import-sort/imports: off

  - files: src/store/**/*.slice.js
    rules:
      no-param-reassign:
        - error
        - props: true
          ignorePropertyModificationsFor: [state]

settings:
  import/resolver:
    webpack:
      config: './config/webpack.common.js'
